group: deprecated-2017Q2
sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - "8"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

env:
  DOCKER_COMPOSE_VERSION :1.12.0

cache:
  directories:
    - node_modules

before_install:
  - npm install npm@5 -g
  - npm install -g @angular/cli@latest
  - npm install -g karma
  - npm install -g mocha
  - npm install -g node-sass
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install -U docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose build && docker-compose up -d mongodb node
  - chmod ugo+x install.sh
  - sudo chown -R travis ./
  - chmod 777 server
  # - whoami
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - ./install.sh

script: npm run server:test && ng test